### ISSUE TITLE
Weird `require.extensions` after requiring mock-fs

### ISSUE THREAD

**Issue by tomekwi** [tschaub/mock-fs#115]
Hi, thanks for this great library!

I run into a problem with mock-fs setting a weird `{ '.coffee': undefined }` property on the global `require.extensions` object. This caused [a problem](https://github.com/fgnass/node-dev/pull/134) when paired with [node-dev](https://github.com/fgnass/node-dev). The problem I’ve described in the PR only appears when I `require('mock-fs')` in my tests.

I’ve fixed the interop on the node-dev side, so it’s not an urgent thing for me. But you might want to investigate this further.

**Comment by tschaub** [comment]
Thanks for the report.  It looks like this is added by the [`rewire` package](https://www.npmjs.com/package/rewire).

I've proposed https://github.com/jhnns/rewire/pull/98 as a fix for the issue.  I'll leave this open until it is addressed upstream and we can pull in a fix here.

**Comment by tschaub** [comment]
Fix pulled in with #132.  No more weird `require.extensions` properties in the next release.

**Comment by tomekwi** [comment]
🙌
