### ISSUE TITLE
Question-  /path/to/file is not being mocked

### ISSUE THREAD

**Issue by dman777** [tschaub/mock-fs#123]
Unit testing my gulp app in Mocha and using `mock-fs`.

In my app code I have:

```javascript
    console.log('sssssssssssssss ' + srcFile);
    srcFile = fs.statSync(srcFile).mtime;
```
which shows `sssssssssssssss /home/one/foo`

In my test I have:
```javascript
        mock({
            home: {
              one: { 
                foo: mock.file({
                  content: 'nothing',
                  mtime: new Date(Date.now())
                })
              },
            },
            bar: mock.file({
            content: 'nothing',
            mtime: new Date(1,1)
            })
        });
```

But I get the error `Error: ENOENT, no such file or directory '/home/one/foo'` when I run  the test. 

What I am doing wrong where `/home/one/foo` is not being mocked?

**Comment by tschaub** [comment]
Try changing `home` (a relative path) to `/home` (an absolute path).

E.g.

```js
mock({
  '/home': {
    one: {
      foo: mock.file({
        content: 'nothing',
        mtime: new Date()
      })
    }
  }
});
```

By default, `process.cwd()` is created for you.  If you use relative paths, files will be created relative to `process.cwd()` (as with the real `fs` functions).  You need to use absolute paths (e.g. `mock({'/foo/bar/bam': 'baz'})` if you want to start by creating files at the root.
