### ISSUE TITLE
rimraf not working

### ISSUE THREAD

**Issue by nkint** [tschaub/mock-fs#135]
Hi! 
I'm using `mock-fs` in some tests but I'm not able to execute `rimraf` (its callback is never called).

This is very annoying because it seems to be a side effect: also without using `mock-fs` explicitly, just requiring it brokes my `rimraf` code.

How can I do it?

**Comment by tschaub** [comment]
If you can provide a simple example that demonstrates your problem, that will make it easier for someone to reproduce any issue you are seeing.

**Comment by tschaub** [comment]
Please reopen with additional detail (e.g. sample code that reproduces your problem) if you can reproduce this with the latest release.
