### ISSUE TITLE
Node 7 support

### ISSUE THREAD

**Issue by goliney** [tschaub/mock-fs#173]
[Node 7 has been released](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md)
It would be great if mock-fs supported it.

**Comment by goliney** [comment]
@tschaub , sorry for bothering you, but could you please take a look.

**Comment by medecau** [comment]
If you installed nodejs on OSX using Homebrew and the update to 7 is giving you headaches:

- `brew uninstall node`
- `brew install node6-lts`

**Comment by tschaub** [comment]
Node 7 support added in `mock-fs@3.12.0`.  Thanks for the contribution @goliney.
