### ISSUE TITLE
Problem with stub fs.WriteStream

### ISSUE THREAD

**Issue by blond** [tschaub/mock-fs#176]
The problem is reproduced because #139.

**Versions:**
- `mock-fs`: `v3.11.0` and `v3.12.0` 
- `sinon`: `1.17.6` 
- `Node.js`: `v4.6.1` and `v6.9.1` 

**Example:**

I want stub `fs.WriteStream`. If I don't use `mock-fs`, then instance of `writeStream` has the `on` method.

``` js
var fs = require('fs');
var sinon = require('sinon');

var writeStream = sinon.createStubInstance(fs.WriteStream);

console.log(writeStream.on); // { [Function: proxy], ... }
```

If I require `mock-fs`, then the `on` method is lost.

``` js
var fs = require('fs');
var sinon = require('sinon');

require('mock-fs');

var writeStream = sinon.createStubInstance(fs.WriteStream);

console.log(writeStream.on); // undefined
```

**Comment by jpfranco** [comment]
I'm having the exact same issue.

**Comment by jpfranco** [comment]
Btw, this seems to have been introduced in 3.11.0. I downgraded to 3.10.0 and the issue is gone.

**Comment by blond** [comment]
@jpfranco yeah, see #139

**Comment by tschaub** [comment]
This script works with `mock-fs@4`:

```js
var fs = require('fs');
var sinon = require('sinon');

require('mock-fs');

var writeStream = sinon.createStubInstance(fs.WriteStream);

console.log(writeStream.on);
```

**Comment by danielo515** [comment]
I'm having the same issue with the write method:

```js
            Mock ({
                'testFile': 'file contents'
            });
            const stubStream = Sinon.stub (fs.createWriteStream ('testFile', { flags: 'a' }), 'write');
            stubStream.write // => undefined
```

Maybe it is wrong use of the api of sinon ? 

* mock-fs@4.6.0
* sinon@6.1.5

**Comment by danielo515** [comment]
Ok, my bad.
Seems that stub does not returns the stubbed object, but the stubbed method. It actually mutates the object in place.
fine
