### ISSUE TITLE
Run ava with mock-fs causes an error in Node 7.7.2

### ISSUE THREAD

**Issue by sqrthree** [tschaub/mock-fs#199]
When I run `ava` with mock-fs in `Node 7.6.0`, it works well. But I got this following error when I update Node.js to `7.7.2`.

```
Error: ENOENT, no such file or directory '/node_modules/ava/lib/test-worker.js'
```

I'm not sure it's because of `mock-fs` or `ava`. You can get more detail at https://travis-ci.org/sqrthree/gitmit/jobs/210002481#L935

**Comment by tschaub** [comment]
Please reopen if this is still an issue with `mock-fs@4.2.0`.

**Comment by sqrthree** [comment]
thanks for your work, looks like it works well with node stable version. 👍

**Comment by pscanf** [comment]
I get a similar error running `mocha` (with the typescript require-hook):

```
$ NODE_ENV=test mocha --compilers ts:ts-node/register --recursive --timeout 5000
Error: ENOENT, no such file or directory '[...]/test/setup.ts'
```

I get the error with `mock-fs@v4.2.0` with either `node@v6.10.2`, `node@v7.6.0` and `node@v7.8.0`.

I don't get any errors with `mock-fs@v3.12.1`.

Could it be the same cause? (Should I open a separate issue providing more details?)
