### ISSUE TITLE
tape stops logging when using mock-fs

### ISSUE THREAD

**Issue by nemoxps** [tschaub/mock-fs#201]
> I'm not sure what's going on, but if `mock-fs` can't handle `fs.writeSync(1, content)`, then it might be a bug in that library.

Take a look at https://github.com/substack/tape/issues/354.

**Comment by tschaub** [comment]
Thanks for the report @nemoxps.

**Comment by ryanblock** [comment]
This bit me today (in Windows, not on Mac or *nix), any thoughts on how we might approach a fix?

**Comment by tschaub** [comment]
Here is one approach: https://github.com/tschaub/mock-fs/commit/80d318f51a2f06023f27e39662171882a2b34f45.  This only works for stdin/out/err streams connected to a text terminal.  For non-TTY environments, the process never exits – I didn't spend enough time to figure it out, but maybe someone else can.  There are likely other ways to bypass the mock filesystem for the special 0, 1, and 2 file descriptors.

**Comment by ryanblock** [comment]
I'm back because I was once again bitten by this bug! (lol)

No opinion on that specific fix but in theory I'm happy to help write some tests around this.

**Comment by filmaj** [comment]
I have also been bit by this bug 🙈 

Same here, I am not familiar enough with mock-fs internals to say which approach should be taken, but for what it is worth, the `std` branch of mock-fs fixes the issue! (I tried it out on a PR in our project: https://github.com/architect/logs/pull/311)

**Comment by filmaj** [comment]
Friendly bump 😄 
I hit this bug again today haha. I always forget about this, and then remember, and end up back here.
What are the chances of getting the `std` branch that is pushed up to the origin of this repo merged into mainline?

**Comment by tschaub** [comment]
See how things go with `mock-fs@4.14`.

**Comment by filmaj** [comment]
Awesome, thanks so much @tschaub ! Works great for us over in the @architect project!
