### ISSUE TITLE
Using in memory filesystem as a drop in replacement for CLI tool chain

### ISSUE THREAD

**Issue by megamindbrian** [tschaub/mock-fs#211]
What do you think of this?

https://github.com/webpack/memory-fs/issues/43

**Comment by streamich** [comment]
You might want to try my [`memfs + unionfs + fs-monkey`](https://github.com/streamich/memfs#see-also) setup.

**Comment by tschaub** [comment]
I'll close this since I don't think it describes an issue related to this repository that someone can act on.
