### ISSUE TITLE
TypeError: binding.FSInitialize is not a function

### ISSUE THREAD

**Issue by ssimpo** [tschaub/mock-fs#219]
I am getting this error using node v8.4.

Is this error easy to fix  or is it a major headache? I can see the various for different node versions in /node.  Is is possible for me to hack this somehow to get my tests running on version 8.

**Comment by tschaub** [comment]
What version of `mock-fs` are you using?  Also, can you include a stack trace or a bit more detail about the test that is failing?

**Comment by ssimpo** [comment]
Thanks, that pointed me in the right direction.

Sorry, I was using an old version. I'd done a 'yarn upgrade' but looks like I forgot to add latest.  I therefore assumed I was using the latest version but was not.

Sorry for wasting your time.
