### ISSUE TITLE
mocking image files

### ISSUE THREAD

**Issue by hellboy81** [tschaub/mock-fs#23]
I am testing module that loads/saves images from files in `PNG`, `JPEG` and other formats.

Image fixtures can be stored
- on real file system in test fixtures directory
- on mocked file system using `mock-fs`

With the the second option I have problem: How can I generate random file content in JPEG/PNG format?  For example:
```js
'/var/files/my.jpg': mockFs.file({
   content: faker.image(...,'JPEG',....)
})
```

Is there faker modules for Node.js?

**Comment by tschaub** [comment]
I don't have experience generating valid JPEG or PNG files with random content, but I assume [`jpeg-js`](https://www.npmjs.com/package/jpeg-js) and [`pngjs`](https://www.npmjs.com/package/pngjs) could be used.

A third alternative is to include a few images as test fixtures in your repo and in your test setup, copy them to a mock filesystem.  Then all your tests operate on the mock files, but you don't have to do extra work to correctly mock the images.  I've used this pattern elsewhere and it works pretty well - in your test setup, read your fixtures into buffers and then set up the mock filesystem with those buffers as content where you need it.

**Comment by hellboy81** [comment]
One more question: Is there possible to save mocked fs state to facilitate post-portem analyze of unit tests results?

**Comment by tschaub** [comment]
There's nothing built in to dump the mock filesystem contents.  Though it should be possible to write a small utility that walked the filesystem tree from the root and generated a single structure containing all file contents.
