### ISSUE TITLE
What about events for fs actions?

### ISSUE THREAD

**Issue by zxqfox** [tschaub/mock-fs#24]
Thanks for a great tool!

I'm stuck with a trouble of testing caching.
In my case I need to test of how many times file was read. But it's also could be useful to checking all actions on mocked fs.

p.s. For sure I can use sinon for that.

**Comment by tschaub** [comment]
It should be possible to add support for [`fs.watch`](http://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener) and extend it to support more events.
