### ISSUE TITLE
Question: does accessSync not work with this library? 

### ISSUE THREAD

**Issue by begin-again** [tschaub/mock-fs#248]
Does `accessSync` not work with this library? The below assert is returning undefined `AssertionError [ERR_ASSERTION]: undefined == true`

```javascript
const fs = require('fs');
const fakeFS = require('mock-fs');
const assert = require('assert')

fakeFS({
    './fakeFile': { }
});
assert.ok(fs.accessSync('./fakeFile', fs.constants.F_OK));
```

**Comment by tschaub** [comment]
@maxwellgerber's answer looks right to me.  Please reopen if you find the `mock-fs` behavior different than regular `fs` behavior.
