### ISSUE TITLE
fs.readdir seems broken since Node 10.10.0

### ISSUE THREAD

**Issue by kibertoad** [tschaub/mock-fs#250]
"fs.readdir" -> "lists nested directory contents" test is timing out in Node.js 10.10.0 and this seems consistent with what we are seeing in Knex.js tests that rely on mock-fs.

**Comment by maxwellgerber** [comment]
This is caused by the addition of `fs.Dirent` objects in `10.10.0`, which changed the API of `binding.readDir`.
See:
https://github.com/nodejs/node/blob/master/lib/fs.js#L789
https://nodejs.org/api/fs.html#fs_class_fs_dirent
