### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by julien-f** [tschaub/mock-fs#26]
I have not taken a deep look but it seems that this module does not work with io.js.

**Comment by tschaub** [comment]
See #21.  This was [released in 2.5.0](https://github.com/tschaub/mock-fs/commit/25969e84547cbf4d15bc0eaaceb39167bec9ae3a).

Please reopen a more specific ticket with details of any failures you notice with io.js.

**Comment by julien-f** [comment]
Ok, will do when I have time to investigate.
