### ISSUE TITLE
errors when upgrading to node 10

### ISSUE THREAD

**Issue by travi** [tschaub/mock-fs#270]
with https://github.com/tschaub/mock-fs/issues/257 fixed, i attempted again to upgrade [a project of mine](https://github.com/travi/javascript-scaffolder/tree/node-10) to node 10, but was presented with new errors that appear to be related to the mocked filesystem. i've been using the package in a cli that runs in node 10 for a while now and have not run into these errors outside of this testing scenario.

the primary error that i'm seeing now is:

```
Error: EEXIST, file already exists '...path-to-project/javascript-scaffolder/test/unit'
           at Object.<anonymous> (...path-to-project/javascript-scaffolder/node_modules/mock-fs/lib/binding.js:939:13)
           at maybeCallback (...path-to-project/javascript-scaffolder/node_modules/mock-fs/lib/binding.js:68:18)
           at Object.Binding.mkdir (...path-to-project/javascript-scaffolder/node_modules/mock-fs/lib/binding.js:936:3)
           at Object.<anonymous> (...path-to-project/javascript-scaffolder/node_modules/mock-fs/lib/index.js:33:39)
           at mkdir (fs.js:735:11)
           at Promise (internal/util.js:274:30)
           at new Promise (<anonymous>)
           at mkdir (internal/util.js:273:12)
           at makeDir (...path-to-project/javascript-scaffolder/node_modules/make-dir/index.js:52:9)
           at exports.default (...path-to-project/javascript-scaffolder/src/linting/eslint.js:13:50)
           at process._tickCallback (internal/process/next_tick.js:68:7)
```

when attempting to [create a directory](https://github.com/travi/javascript-scaffolder/blob/9bcbef6eb7be7525999ede2acc5eea1aaad0f0d4/src/linting/eslint.js#L13). i have not seen such an error at runtime against a real file system, even when scaffolding over an existing project where that directory is sure to exist.

i'm also seeing the following error at the end of my test suite, but without a stack trace. i'm not sure if it is a result of the other errors happening earlier in the test run or not.

to reproduce, clone [my project](https://github.com/travi/javascript-scaffolder) and run `npm run test:integration` to see that everything passes in the `master` branch. then switch to the `node-10` branch and run the same script to see the errors.

are there still outstanding, known changes necessary for mock-fs to handle actions like this in node 10?

**Comment by 3cp** [comment]
There is a behaviour difference between real nodejs call and my mock-fs implemnetation.

It's about mkdir on existing folder.

Nodejs complains nothing with recursive mode on, but complains EEXIST with recursive mode off.

My implementation inherited the default behaviour from an old implementation, which always complains EEXIST.

Will be fixed plus test coverage.

**Comment by travi** [comment]
thanks @3cp and @tschaub. i'll give it another try once the new version is available

**Comment by tschaub** [comment]
Fix published with `mock-fs@4.10.1` (thanks @3cp).

**Comment by travi** [comment]
with this update, i'm now seeing the following error instead:

```
Error: EBADF: bad file descriptor, read
```

this one doesn't show a stack trace, so it's not obvious how to track it further. 

i did push the update to the `node-10` branch that i linked to above, if it would help give me any hints of what else to look into.

**Comment by 3cp** [comment]
You can try catch your mkdir line (or maybe the writeFiles too) to print out stack trace.

**Comment by travi** [comment]
i was able to resolve the issue for this project by switching from `mz/fs` to `fs/promises` for a few `readFile` calls in the tests. i haven't yet migrated everything in the project away from `mz/fs` yet, but this seems to be enough to get my tests passing at least.

is there something different about `mz/fs` under node v10 that would make it behave differently against `mock-fs`?

**Comment by 3cp** [comment]
Because you have deep dependency on `graceful-fs`, and `mz` actually loads it instead of normal `fs`.

https://github.com/normalize/mz/blob/f3d4c7933ab03ad60353bacd70663614ab4482e9/fs.js#L4-L8

From mock-fs readme, when using `graceful-fs`, you need to mock before load `graceful-fs` module. That's definitely not possible with your static import.

When you use `fs/promises`, everything just work as expected.

**Comment by travi** [comment]
thanks. its interesting that i didnt have trouble before the node v10 upgrade if thats the case. i'm working through similar issues in another project that i expect have a similar cause. seems like i should just need to work through eliminating `mz/fs`

**Comment by 3cp** [comment]
I am not sure about what happened then. I have never used graceful-fs.
