### ISSUE TITLE
Mock a call to return an error

### ISSUE THREAD

**Issue by TheSavior** [tschaub/mock-fs#28]
I want to test that my code fails gracefully if there is an error reading or writing to the file system.

Do you have any recommendations on how to cause this to occur?

**Comment by tschaub** [comment]
I'd suggest setting up the mock with the situations you want to test.  If you want to test that your code handles `ENOENT` gracefully, try reading a file that doesn't exist.  If you want to test that you handle `EACCES` gracefully, try reading a file without read permissions.  Not all errors thrown from the real `fs` module are thrown by the mock, but you should be able to cover common cases.  If there is a specific error you want to test that is not covered (e.g. `EMFILE`), that would make a good feature request or pull request.
