### ISSUE TITLE
[feature] control speed of writing/reading.

### ISSUE THREAD

**Issue by Floby** [tschaub/mock-fs#30]
I still have to figure out how this would be exposed, but I need to test some case where there might be some concurrency between read and writes. Namely I have to test that locking mechanisms in place are efficient.

It would be useful to be able to mock a file's streaming speed.

**Comment by tschaub** [comment]
This sounds like a nice feature, but I can't see a way to implement it without making a mess of things.  It would be fairly straightforward to add a delay to every call to the binding, but I don't think this is what you're after, and even this would be a bit of a hack.

If someone comes along with a pull request or a great suggestion about how to implement this, I think it's worth considering.  But I'm going to close this for now as it is not something I'm going to take on.

**Comment by Floby** [comment]
Yes, I agree.
It turns out I was able to do something decent with sinon.js and [slow-stream](https://www.npmjs.com/package/slow-stream)

**Comment by zxqfox** [comment]
Suggestion:
```js
mock.file({
  delay: Number
})
```

And in code just:
```
fs.readFile = function(file) {
  …
  if (files[file].delay) { setTimeout(() => cb(res), files[file].delay) } else { cb(res); }
  …
}
```

Why mess?
