### ISSUE TITLE
Fails to load JSON with escape character

### ISSUE THREAD

**Issue by dbmundell** [tschaub/mock-fs#310]
When loading a JSON formatted fake file like this:

{
  "something": "ONE-THING\tANOTHER "
}

I get an error saying that an unexpected character was found - removing \t successfully loads the file

**Comment by 3cp** [comment]
There is nothing wrong at mock-fs side. You probably has code to trigger that error after reading file content.

Following code runs as expected.
```js
const fs = require('fs');
const mockfs = require('mock-fs');

mockfs({
  "something": "ONE-THING\tANOTHER "
});

const content = fs.readFileSync('something', 'utf8');
console.log(content);
```

**Comment by 3cp** [comment]
Note if you write the file content in code, you have to escape `\` for the json file.
```js
mockfs({
  "a.json": `{"something":"ONE-THING\\tANOTHER "}`
});
