### ISSUE TITLE
createWriteStream is not mocked in node 16/17

### ISSUE THREAD

**Issue by BuZZ-T** [tschaub/mock-fs#343]
Hi! I observed the following problem using mock-fs:

I've written a file using fs.createWriteStream:
https://github.com/BuZZ-T/rusted-chromium/blob/35bd03817439545ec52c66a4a75d93acb13eb477/download.ts#L87
```
const file = createWriteStream(downloadPath + '.zip')
// ...
zipFileResponse.body.pipe(file)
```
and checked if it's written properly using mock-fs:
https://github.com/BuZZ-T/rusted-chromium/blob/35bd03817439545ec52c66a4a75d93acb13eb477/download.int.spec.ts#L113
```
expect(existsSync(chromeZip10)).toBe(true)
```

This works on node 14. When running the tests with node 16 or 17, the tests fail:
https://app.travis-ci.com/github/BuZZ-T/rusted-chromium/builds/241287559

When i run the tests locally with node 16 and 17, i can see that the file is created in the real filesystem.
The functionality with the unmocked createWriteStream is working properly and the same for all tested node versions.

Am i doing sth. wrong, or is this a bug of mock-fs?

Thx for your help and your great work!

**Comment by 3cp** [comment]
Nodejs v16+ has a breaking change on the timing of read/write steam.
https://github.com/tschaub/mock-fs/issues/338#issuecomment-962393651
(more details on the previous comment above this one)

You could try to check existsSync in a "close" or "finish" event callback of the stream, that probably will straighten the timing.

**Comment by 3cp** [comment]
Or try to add an awaited delay. https://github.com/tschaub/mock-fs/issues/338#issuecomment-962390017

**Comment by 3cp** [comment]
I deleted my previous reply, after I realised you said the file was created in real file system. It's bit odd, I checked out unit test code, it seems createWriteStream is creating mocked file just fine in node v16.

**Comment by 3cp** [comment]
Can you check node 14, whether your test code generates file in **real** file system too?

**Comment by 3cp** [comment]
What I guess is that your async `downloadChromium` function didn't wait for the write steam to finish writing.
It might be the similar timing issue as createReadSteam in nodejs v16+ https://github.com/tschaub/mock-fs/issues/338#issuecomment-962393651

You probably can try using the write stream's "close" or "finish" event callback to mark the ending of `downloadChromium`.

**Comment by BuZZ-T** [comment]
Hi 3cp! No, using node 14 no file is created in the real fs.

Thx for the hint with the timing issue, i'll check that!

**Comment by BuZZ-T** [comment]
Sorry for the late feedback. @3cp was right, error was on my side. It's working now! I appreciate the support and your work!
