### ISSUE TITLE
uvBinding.getErrorMap is not a function

### ISSUE THREAD

**Issue by MatiasDelorenzi** [tschaub/mock-fs#345]
I'm using mocha/chai in this project and when I run my tests locally it works just fine, but when I push them to gitlab it throws this error in the pipeline. 

`{"error":{"name":"TypeError","message":"uvBinding.getErrorMap is not a function","stack":"TypeError: uvBinding.getErrorMap is not a function\n    at Object.<anonymous> (.../node_modules/mock-fs/lib/error.js:10:11)`

I can't share much code because It's from the company I work for, but I'm calling the module like:

```
const mock = require('mock-fs)
...

describe( 'test', function(){
 it('should mock filesystem, function() {
    mock({
        'path-to-file': JSON.stringify(ObjectStub)
    });
    ....
    mock.restore()
    })
})
```

**Comment by 3cp** [comment]
Check your gitlab ci nodejs version. Latest mock-fs only supports nodejs v12+.

**Comment by danilobassi8** [comment]
> 

Thanks! Worked for me.
