### ISSUE TITLE
Different behavior with yauzl

### ISSUE THREAD

**Issue by regseb** [tschaub/mock-fs#352]
The [yauzl](https://github.com/thejoshwolfe/yauzl) library has a different behavior with mock-fs.

```JavaScript
import mock from "mock-fs";
import yauzl from "yauzl";

if (process.argv.includes("mock")) {
    mock({ "baz.zip": mock.load("baz.zip") });
}

const zipfile = await new Promise((resolve, reject) => {
    yauzl.open("baz.zip", (err, zipfile) => {
        if (err) reject(err);
        resolve(zipfile);
    });
});
zipfile.on("error", (err) => console.log("error", err));
zipfile.on("entry", (entry) => console.log("entry", entry.fileName));
zipfile.on("end", () => console.log("end"));
```

The above code prints :

- without the _mock_ argument: `entry foo.txt` and `end`
- with the _mock_ argument : `end`

I think the problem is that mock-fs does not call IO and returns the result directly ([_Event Loop_](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/)). Because without the promise, the behavior is the same.

```JavaScript
yauzl.open("baz.zip", (err, zipfile) => {
    if (err) throw err;
    zipfile.on("error", (err) => console.log("error", err));
    zipfile.on("entry", (entry) => console.log("entry", entry.fileName));
    zipfile.on("end", () => console.log("end"));
});
```

To reproduce the problem:

- Download and unzip [testcase.zip](https://github.com/tschaub/mock-fs/files/8177037/testcase.zip)
- `npm install`
- `node fail.js`
- `node fail.js mock`

**Comment by 3cp** [comment]
With nodejs v14.18.1 and v16.13.2, I am seeing both fail.js and success.js output same correct result.
```
huocp@Chunpengs-MacBook-Pro ~/D/testcase> node fail.js
entry foo.txt
end
```

What's your nodejs version?

**Comment by regseb** [comment]
@3cp

- node: v16.14.2
- npm: 8.5.5
- Ubuntu: 20.04.4 LTS

The scripts have a `mock` parameter to activate mock-fs. `node fail.js` launches the reading of the zip without anything mocked. `node fail.js mock` launches the reading of the zip with mock-fs. `success.js` works with and without mock-fs. But `fail.js` doesn't work with mock-fs.

<table>
  <tr>
    <th><code>node fail.js</code></th>
    <th><code>node fail.js mock</code></th>
    <th><code>node success.js</code></th>
    <th><code>node success.js mock</code></th>
  </tr>
  <tr>
    <td><pre><code>entry foo.txt
end</code></pre></td>
    <td><pre><code>end</code></pre></td>
    <td><pre><code>entry foo.txt
end</code></pre></td>
    <td><pre><code>entry foo.txt
end</code></pre></td>
  </tr>
</table>

**Comment by 3cp** [comment]
My bad, I missed the mock argument. I can reproduce the issue on both node v14 and v16.

**Comment by 3cp** [comment]
I don't quite understand this Nodejs (or JavaScript) feature, the promise that handles events "error", "entry" and "end". I thought only the reject and resolve calls interact with the promise itself?
Is there some official document around the wrapped promise becoming an event target?

**Comment by regseb** [comment]
The variable `globalZipfile` contains the value of the variable `callbackZipfile`. The [`await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) waits the promise and returns the fulfilled value of the promise (or throws an error if the promise is rejected).

```JavaScript
const globalZipfile = await new Promise((resolve, reject) => {
    yauzl.open("baz.zip", (err, callbackZipfile) => {
        if (err) reject(err);
        resolve(callbackZipfile);
    });
});
```

**Comment by regseb** [comment]
Here is another test case using [`setImmediate()`](https://nodejs.org/api/timers.html#setimmediatecallback-args) that fails with mock-fs.

```JavaScript
import mock from "mock-fs";
import yauzl from "yauzl";

if (process.argv.includes("mock")) {
    mock({ "baz.zip": mock.load("baz.zip") });
}

yauzl.open("baz.zip", (err, zipfile) => {
    if (err) throw err;
    setImmediate(() => {
        zipfile.on("error", (err) => console.log("error", err));
        zipfile.on("entry", (entry) => console.log("entry", entry.fileName));
        zipfile.on("end", () => console.log("end"));
    });
});
```

**Comment by 3cp** [comment]
Oh, I see. I got confused. It's the resolved value in play.

**Comment by 3cp** [comment]
Feels like another timing issue because of our readStream patch.
The zipfile already emitted those entry events before the promise exercise the `.then(resolved => {...})`.
The lazyEntries mode of yauzl seems work as expected.
