### ISSUE TITLE
`lutimes` not supported?

### ISSUE THREAD

**Issue by steilerDev** [tschaub/mock-fs#365]
I'm currently testing an app using mock-fs. This app uses [`fs.promises.lutimes` and `fs.lutimesSync`](https://nodejs.org/api/fs.html#fslutimessyncpath-atime-mtime) to change the timestamp of symbolic links generated. Is it possible, that mockfs is not supporting this function (as `lutimes` throws a 'file not found' error, when using mock-fs, however I could not find any mention of this anywhere in this repo)

Thanks!

**Comment by 3cp** [comment]
I see lutimes was added in: nodejs v14.5.0, v12.19.0.
It should be possible to add the support.

**Comment by 3cp** [comment]
While working on this, also discovered that our utimes implementation has a bug, it should follow symlink but it doesn't.
