### ISSUE TITLE
Does not support 2.0.0 version of io.js

### ISSUE THREAD

**Issue by scurker** [tschaub/mock-fs#39]
It seems that support for the newest version of io.js needs to be added, as running mock against the latest version gives the error: `Error: Unsupported Node version: 2.0.0`

According to the [2.0 changelog](https://github.com/iojs/io.js/blob/master/CHANGELOG.md) it doesn't appear that there are any breaking changes.

**Comment by tschaub** [comment]
Fixed with #38 and published as `mock-fs@2.7.0`.
