### ISSUE TITLE
mock-fs not compatible with graceful-fs >= 3.0.0

### ISSUE THREAD

**Issue by psalaets** [tschaub/mock-fs#42]
I am trying to use mock-fs to fake a file system and then perform reads using (a module that uses) graceful-fs.

Running this code:

```js
var mock = require('mock-fs');
var graceful = require('graceful-fs');

mock({
  dir: {
    file1: 'contents of file1'
  }
});

var file1 = graceful.readFileSync('./dir/file1', {encoding: 'utf8'});

console.log(file1);
```
gives me

```
Error: ENOENT, no such file or directory './dir/file1'
```

Loading my package.json with this same code printed out fine. So looks like graceful-fs is reading from the real file system.

Based on the [caveats section](https://github.com/tschaub/mock-fs/blob/master/readme.md#caveats) in the readme this should work. Am I doing something wrong here? 

My versions are
```
node        0.10.36
graceful-fs 3.0.7
mock-fs     2.7.0
```

**Comment by psalaets** [comment]
(Leaving this info here for others)

The code example above works with `graceful-fs@2.0.3` and breaks with `graceful-fs@3.0.0`.

Which I think is due to changes in https://github.com/isaacs/node-graceful-fs/commit/08471b246bec73848b53e9ad4972f5fe02031805

**Comment by tschaub** [comment]
This is unfortunate, but not totally unexpected.  We could escalate the monkey patching war by overriding `process.binding`, but that may be pushing it.

**Comment by isaacs** [comment]
That test script works for me on graceful-fs@4.1.2

**Comment by tschaub** [comment]
Thanks for weighing in @isaacs.  Will update the docs.
