### ISSUE TITLE
Mocking file system contents not working with gulp.src

### ISSUE THREAD

**Issue by ErikEvenson** [tschaub/mock-fs#44]
http://stackoverflow.com/questions/30602416/mocking-file-system-contents-not-working-with-gulp-src

I'm trying to use [mock-fs][1] to mock up file system contents to test gulp tasks.  Unfortunately, `gulp.src` doesn't seem to play well with `mock-fs`.  Specifically, I get ENOENT errors:

    Message:
        ENOENT, lstat '/vagrant/study-node-heroku/instances/development/app.json'
    Details:
        errno: -2
        code: ENOENT
        path: /vagrant/study-node-heroku/instances/development/app.json
        domainEmitter: [object Object]
        domain: [object Object]
        domainThrown: false
    Stack:
    Error: ENOENT, lstat '/vagrant/study-node-heroku/instances/development/app.json'
        at Error (native)

Other parts of my code and test code access the `mock-fs`-created files just fine.

What am I doing wrong?  I suspect that the problem is related to gulp's usage of vinyl.

Here is the function under test:

    var herokuTarball = function(options, done) {
      var instance = options.instance || 'development';
      var tarballName = options.tarballName || instance
      var tarballPath = path.join(config.temp, tarballName + '.tar.gz');
      var files = path.join(config.instances, instance, '**/*');
      yassert.file(path.join(config.instances, instance, 'app.json'));
    
      async.waterfall([
        function(cb) {
          del([tarballPath], cb);
        },
        function(err, cb) {
          gulp.src(files)
            .pipe(tar(tarballName + '.tar'))
            .pipe(gzip())
            .pipe(gulp.dest(config.temp))
            .pipe(gcallback(cb));
        }
      ], function(err, result) {
        if (err) return err;
        return done(err, tarballPath);
      });
    }

And here is the test snippet:

    describe('gulp heroku:tarball', function() {
      after('something', function() {
        mock.restore();    
      });
    
      before('something', function() {
        mock({
          'instances/development': {
            'app.json': 'test content'
          }
        });
      });
    
      it('creates a tarball', function(done) {
        var options = {}
    
        heroku.herokuTarball(options, function(err, result) {
          expect(result).to.be.a('string');
          yassert.file(result);
          done();
        });
      });
    });

Notice that the yassert (yeoman-assert) calls pass fine -- the file is there.  If I take the function with the gulp.src call out of the async waterfall, the error goes away (and the test fails of course).

  [1]: https://www.npmjs.com/package/mock-fs

**Comment by psalaets** [comment]
I think you are running into #42 

gulp.src uses vinyl-fs which uses graceful-fs

**Comment by ErikEvenson** [comment]
Could be -- but, like you, I haven't found a work-around or what I am doing wrong.

**Comment by JohnBaileyN** [comment]
I am facing this same issue.

**Comment by tschaub** [comment]
Things should be working with `graceful-fs>=4` (see #48).
