### ISSUE TITLE
How to assert on created files?

### ISSUE THREAD

**Issue by city41** [tschaub/mock-fs#50]
My app creates files, and I want to do assertions against those created files. As far as I can tell, mock-fs is only allowing you to provide already existing mock files.

I do something like
```
mock({'fake/dir': {}});

myAppComponentCreateAFile('fake/dir/myfile.txt');

// this doesn't exist, wishful thinking
expect(mock.getFileContents('fake/dir/myfile.txt')).to.eql('contents of my created file');
```

I found if I have the main `mock()` return the `FileSystem` it creates, I can them do

```
var filesystem = mock({'fake/dir': {}});
myAppComponentCreateAFile('fake/dir/myfile.txt');
expect(filesystem.getItem('fake/dir/myfile.txt')._contents.toString()).to.eql('contents of my created file');
```

I just did this by adding `return system` at the bottom of `mock()`. Is there a better way that I missed?

Thanks for the useful module btw!

**Comment by tschaub** [comment]
You can use the `fs` methods to work with your mocked files.
