### ISSUE TITLE
Doesn't work with node 4.2.1

### ISSUE THREAD

**Issue by erbridge** [tschaub/mock-fs#66]
I get the following error:

```
Error: Unsupported Node version: 4.2.1
    at Object.<anonymous> (/path/to/project/node_modules/mock-fs/lib/index.js:34:9)
```

**Comment by alexbooker** [comment]
Me too :cry:

**Comment by alexbooker** [comment]
Support for Node 4.0.0 was only recently [**added**](https://github.com/tschaub/mock-fs/pull/65). The [**npm package**](https://www.npmjs.com/package/mock-fs) needs updating.

**Comment by tschaub** [comment]
[Version 3.4.0](https://github.com/tschaub/mock-fs/blob/master/changelog.md#340) was published on [Oct 17](https://github.com/tschaub/mock-fs/commit/6b454e99f93e45065fb7f561c63739498c67d706) with support for Node 4.
