### ISSUE TITLE
Node v5.0.x support

### ISSUE THREAD

**Issue by tivac** [tschaub/mock-fs#67]
`/lib/index.js` doesn't list Node v5 in its list of supported environments, so I can't use `mock-fs` based tests in the latest stable build of Node.

**Comment by FlorianLoch** [comment]
I guess this might take some time, because regarding to the changelog of node there are some breaking changes in the fs api...

Would be great to see fs-mock working with node-v5 soon!

**Comment by ariporad** [comment]
+1, Node 5 support would rock!

**Comment by tschaub** [comment]
Support for Node 5 in `mock-fs@3.5.0`.
