### ISSUE TITLE
Support mocking require

### ISSUE THREAD

**Issue by Kureev** [tschaub/mock-fs#70]
Hey @tschaub! Any plans to include `require` mocks? Probably I can help you with it, just tell me if you want this feature or not.

**Comment by tschaub** [comment]
@Kureev does [`mock-require`](https://www.npmjs.com/package/mock-require) meet your needs?  I haven't used it, but it looks pretty flexible.

**Comment by Kureev** [comment]
Yeah, I'm using it currently, but it was really confusing to realize you have to use two different libs for mocking similar functionality. Anyway, I solved my problem. So, it's more like a question if you'd like to have this functionality in your lib.

**Comment by grabbou** [comment]
Ha, was going to fill that as well. Would be really cool to have that working.

**Comment by tschaub** [comment]
I think folks would find it surprising if using `mock-fs` always changed the behavior of `require`.  I imagine the majority of use cases involve mocking a filesystem for `fs` calls, but preserving the ability to `require` relative modules.

I like the idea of keeping this packages focussed on mocking a filesystem for `fs` calls and encouraging folks to use `mock-require` to override `require` behavior.  But if someone has ideas on how things could be improved with `mock-fs` overriding `require`, I'd be open to reconsidering (and reopening) this.  Ideally, we could discuss some example configurations and compare to using the two packages separately.

**Comment by zxqfox** [comment]
@tschaub The confusing thing about mocking require with mock-fs is does work with node 0.8-0.12, and doesn't with 4.0+. Anyone who had used mock-fs earlier with require just expecting that this works as it was so it should be fixed somehow or noticed somewhere I guess.
