### ISSUE TITLE
Default directory population

### ISSUE THREAD

**Issue by gustavnikolaj** [tschaub/mock-fs#71]
Hi @tschaub 

Thanks for your awesome work on mock-fs.

I have used it to create a [plugin](https://github.com/unexpectedjs/unexpected-fs) for the [unexpected](http://unexpected.js.org/) assertion framework. It is still not ready for primetime, but I'm using it a few projects myself, and it's already proven really useful.

One of unexpected's greatest strengths are it's async assertions, which in combination with the plugin mentioned before, allows me to write assertions like this:

```js

it('should read from the mock-fs', function () {
    return expect(function (cb) {
        fs.readFile('/data/foobar.txt', cb);
    }, 'with fs mocked out', {
        '/data': {
            'foobar.txt': 'Hello world',
        }
    }, 'to call the callback without error').then(function (fileContent) {
        return expect(fileContent, 'to equal', 'Hello world');
    });
});
```

I'm using mock-fs to create the filesystem and [mountfs](https://github.com/papandreou/node-mountfs), to mount the filesystem on a path specified in the object given to the assertion.

The reason why it's preferable to me, to mount the mocks as subtrees of the filesystem instead of in the root is, that require uses fs to load modules. If I'm testing a module that does lazy loading of modules, it would not work, unless I also added those files to the file system.

Also, wrapping mock-fs into an assertion like this, makes it so that the life time of the mock is tightly coupled to the lifetime of the assertion.

My problem is, that mock-fs populates the mocked fs with some defualt folders.

https://github.com/tschaub/mock-fs/blob/6dde8fb8709c4d97212387174d7ce97faaf8a907/lib/filesystem.js#L39-L56

I would like this to be configurable. If you do an `fs.readdir` on `/data` in the above example, you would not just get `foobar.txt` but also `home` and `tmp` (assuming that you are working on a linux machine and you run your tests from somewhere in the /home folder).

It is a very sensible default for all cases but this specific one where it's mounted on a real fs. :-)

**Comment by tschaub** [comment]
Thanks for the suggestion @gustavnikolaj.  I agree it makes sense to have the default directory population be configurable.

Let me know if you are able to test out the changes in #72 or if this looks like it would work for you.

Unexpected and your plugin look nice.

**Comment by gustavnikolaj** [comment]
Thanks a lot for your quick response! I have tested it out and it works fine for me :-)
