### ISSUE TITLE
Issues with buffers

### ISSUE THREAD

**Issue by maxrimue** [tschaub/mock-fs#88]
Hey there,
first of all, thanks for the module, really enjoying it.

I have a module that does some piping (fetches files and directly saves them), however, when testing it, it fails with this error:
```
  1) downloading Nodes should download a specific version:
     Uncaught TypeError: binding.writeBuffers is not a function
      at writev (node_modules/mock-fs/node/fs-5.0.0.js:1962:11)
      at WriteStream._writev (node_modules/mock-fs/node/fs-5.0.0.js:1984:3)
      at doWrite (_stream_writable.js:290:12)
      at clearBuffer (_stream_writable.js:380:5)
      at onwrite (_stream_writable.js:331:7)
      at WritableState.onwrite (_stream_writable.js:89:5)
      at node_modules/mock-fs/node/fs-5.0.0.js:1946:5
      at wrapper (node_modules/mock-fs/node/fs-5.0.0.js:667:5)
      at node_modules/mock-fs/lib/binding.js:37:9
```
Could this be because the dependencies I used (__got__ and __tar.gz__) are not compatible? The code, if needed, can be found [here](https://github.com/maxrimue/automagic/blob/master/test/index.js#L49).

Thanks

**Comment by tschaub** [comment]
The `fs` module for Node 5 patches `WriteStream` to call a new `binding.writeBuffers()` method.  This method is not included in the mock binding.

It should be fairly straightforward to implement this method.  I don't have time at the moment, but anybody else should feel free to jump in.

**Comment by jeresig** [comment]
Unfortunately I'm hitting this issue as well, causing my test suite to fail. I'm not sure I feel confident enough to fork and write the new method from scratch - although I might if it comes to it. @tschaub any additional thoughts on your end?

**Comment by tschaub** [comment]
I've put together an implementation of `binding.writeBuffers()` but could use some real world test cases.  The [current tests](https://github.com/tschaub/mock-fs/blob/3a78ba48fcb42c7031b41f4c3a41794aa9279ad1/test/lib/index.spec.js#L2880-L2897) piping a read stream to a write stream evidently don't hit the code path that calls `binding.writeBuffers()`.  I'll do some more debugging to figure out what test cases will cover this, but if anybody can submit a simple failing test, that would be great.

**Comment by jeresig** [comment]
@tschaub I have a reduced test case:

```
var fs = require("fs");
var http = require("http");

var mock = require("mock-fs");
var request = require("request");
var formidable = require("formidable");

mock({
    "test.zip": fs.readFileSync("test.zip"),
});

var server = http.createServer(function(req, res) {
    var form = new formidable.IncomingForm();

    // binding.writeBuffers is called somewhere inside here
    form.parse(req, function() {
        res.writeHead(200, {"Content-Type": "text/plain"});
        res.end("DONE");
    });
});

server.listen(4321, function() {
    request.post({
        url: "http://localhost:4321/",
        formData: {
            file: fs.createReadStream("test.zip"),
        },
    }, function(err, res, body) {
        console.log(res.statusCode, body);
        process.exit();
    });
});
```

There are two things that seem to trigger it: The `formidable` plugin parsing the form contents and having a big-enough payload to trigger it. I tried it with small zip files (a couple KB, then a few dozen KB) and neither of them triggered the issue. However if I did it with a "larger" zip file (of a couple hundred KB) then `TypeError: binding.writeBuffers is not a function` error was triggered.

You can get the sample payload that I used here:
http://ejohn.org/files/sample-test.zip

The fact that I used `request` here shouldn't matter as I was just using that to trigger an HTTP request. Let me know if you need anything else to help reproduce this!

**Comment by tschaub** [comment]
Awesome.  Thanks for the reproducible test case @jeresig.  I'll give this a try now.

See #94 for a proposed fix.  As described there, the tests write to a corked stream, which looks to trigger the code path that calls `binding.writeBuffers()`.

**Comment by tschaub** [comment]
@jeresig I get `200 'DONE'` with your test above and the changes in #94.
